# Generated by Django 5.1.1 on 2026-03-08 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='officials', to='complaints.department'),
        ),
    ]
